version: 2
updates:
  # Actions used in workflows
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily

  # Cargo
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily